---

- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Add yum repository
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
    - name: Install python 3.6
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - python36u
        - python36u-libs
        - python36u-devel
        - python36u-pip
