---

- apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - software-properties-common
  when: ansible_distribution == 'Debian'

- yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  when: ansible_distribution == 'CentOS'

- name: install common tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip
    - python-setuptools

